version: "3.9"

services:
  app:
    build: .
    restart: always
    depends_on:
      - redis
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      RD_DB: ${RD_DB:-5}
      RD_HOST: ${RD_HOST:-redis}
      RD_PORT: ${RD_PORT:-6379}
    entrypoint:
      - ./bin/entrypoint.sh
  redis:
    image: redis:alpine
    restart: unless-stopped
