services:
  app:
    build: .
    restart: on-failure
    command: sh -c "python main.py"
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN:?}
      RD_URI: ${RD_URI}
      DB_URI: ${DB_URI}
    networks:
      - storage

networks:
  storage:
    external: true
